### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by slieped** [ShuklaGroup/MaxEntVAMPNet#1]
Hi!
First, congratz on your recently published work. It seems v/ exciting and a grat alternative for adaptive sampling MD analyses.

Thus, I want to try it and see which outcomes I get!

I tried to install  using the .yml file, as stated in the README, but with no success. Dont know why, I was getting an error that the torchaudio package was not found. 

> ResolvePackageNotFound: 
>   - torchaudio

I manage to solve it using a package-by-package installation and now it seems to work correctly.

Any chance to update the .yml file so that it can be correclty (and smoothly) set up the env?
bests,

Victor

**Comment by diegoeduardok** [comment]
Hi Victor!
 
Thank you for pointing this out.  I have edited the environment file and changed the README to address this issue.

Let me know if you encounter other issues!
