### ISSUE TITLE
fhandeler incorrect filename check

### ISSUE THREAD

**Issue by slieped** [ShuklaGroup/MaxEntVAMPNet#2]
I was trying to replicate the short example/tutorial.
When I run the `adaptive_run.collect_initial_data(init_states, n_steps=traj_len, n_repeats=1)` snipped I get the following error:
> File ././round_0/./round_0/villin_traj_0_repeat_0.dcd should exist but was not found

I have done some debugging, and it seems an issue with `list_all_files()` from within FileHandler object. Concretely, line 75 of FileHandler.py `for fname in self.files[subdir]:`  where fname returns the FULL path, and this cause an error when joining it with self.root and subdir.
E.g:
- self.root  ->  './'
- self.subdirs -> ['./round_0']
-  self.files ->  {'./round_0': ['./round_0/villin_traj_0_repeat_0.dcd']}

and this make the output of `list_all_files()` returns:
- `['././round_0/./round_0/villin_traj_0_repeat_0.dcd']`

I solve it modifying the function list_all_files() to:
```
    def list_all_files(self):
        """List all trajectory files handled by this object.

        :return: list.
            List of trajectory filenames.
        """
        filenames = []
        for subdir in self.subdirs:
            for fname in self.files[subdir]:
                filenames.append(fname)

        return filenames 
```
Let me know if something is not clear and I will provide further details.

Victor Montal

**Comment by diegoeduardok** [comment]
Thank you for pointing this out! I have edited the function as you proposed. This should have fixed the problem.
